from summa.summarizer import summarize
from summa.keywords import keywords

text = "Neo-Nazism consists of post-World War II militant social or political movements seeking to revive and implement the ideology of Nazism. Neo-Nazis seek to employ their ideology to promote hatred and attack minorities, or in some cases to create a fascist political state. It is a global phenomenon, with organizedrepresentation in many countries and international networks. It borrows elementsfrom Nazi doctrine, including ultranationalism, racism, xenophobia, ableism, homophobia, anti-Romanyism, antisemitism, anti-communism and initiating the FourthReich. Holocaust denial is a common feature, as is the incorporation of Nazi symbols and admiration of Adolf Hitler. In some European and Latin American countries, laws prohibit the expression of pro-Nazi, racist, anti-Semitic, or homophobic views. Many Nazi-related symbols are banned in European countries (especiallyGermany) in an effort to curtail neo-Nazism. The term neo-Nazism describes any post-World War II militant, social or political movements seeking to revive the ideology of Nazism in whole or in part. The term neo-Nazism can also refer to theideology of these movements, which may borrow elements from Nazi doctrine, including ultranationalism, anti-communism, racism, ableism, xenophobia, homophobia,anti-Romanyism, antisemitism, up to initiating the Fourth Reich. Holocaust denial is a common feature, as is the incorporation of Nazi symbols and admiration ofAdolf Hitler. Neo-Nazism is considered a particular form of far-right politics and right-wing extremism."

print(summarize(text, ratio=0.2))
print("\n\n\n\n\n")
print(summarize(text, words=50))
print("\n\n")
print("Keywords:\n", keywords(text))
print("Keywords:\n", keywords(text, words=3))

textBasket = "Perry Victor Moss (born November 11, 1958) is an American former National Basketball Association (NBA) basketball player. Moss played basketball at Northeastern University under coach Jim Calhoun, where he averaged 15.2 points per game and 3.7 rebounds per game in four seasons there. In his senior season, Moss was named the America East Conference Men's Basketball Player of the Year. Moss graduated as the school’s second-leading career scorer with 1722 points and a 15.2 average in 113 games. He was considered the most explosive guard in New England and one of the most athletic players in the nation. In 1982 he went head to head with future NBA All-Star Dominique Wilkins and the Georgia Bulldogs in the first round of the Gotten State Classic. Despite a big game from Moss, the Huskies lost, but Lakers GM Jerry West, who was in the audience, noted that Moss was the best guard he had seen that year. On his home court, Moss would dazzle the fans with his acrobatic dunks created by his 41-inch vertical leap. As a junior in 1981, Moss teamed with guard Pete Harris to lead the Huskies to their first of seven conference titles. His career included a number of clutch shots, including Moss's halfcourt bomb that sent the championship game versus Holy Cross into overtime, which NU eventually won 76–69. He also hit a last second shot in the opening round of the NCAA tournament when NU knocked off 20th ranked Fresno State before bowing out to Utah. Moss and the Huskies repeated the feat a year later, as Moss averaged 23.7 points per game. NU defeated St. Joseph's 63–62 in the first round, before dropping a heartwrenching, triple overtime affair to Villanova in the second round. Moss scored 23 and 31 points respectively, in those two games. For his career, Moss scored over 30 points eight times and made seven straight all tournament squads. Moss was then drafted with the twenty-third pick in the third round of the 1982 NBA draft by the Boston Celtics, but he was released before playing a single game. Prior to the 1983-84 NBA season Moss was signed by the New Jersey Nets, but was once again released before playing a single game. He played three years in the Continental Basketball Association (CBA) before making his NBA debut for the Washington Bullets in the 1985-86 NBA season. He was released mid-season. Moss finished the 1985–86 season by playing for the Philadelphia 76ers. After the season, Moss was once again released, but he did play for the Golden State Warriors in the 1986-87 NBA season. On Sep 27, 1989, he was signed by the Orlando Magic, but was waived before the start of the regular season. In total, he played in 136 NBA games, and averaged 3.9 points and 1.5 assists."
textNB = "In statistics, naive Bayes classifiers are a family of simple 'probabilistic classifiers' based on applying Bayes' theorem with strong (naive) independence assumptions between the features (see Bayes classifier). They are among the simplest Bayesian network models,[1] but coupled with kernel density estimation, they can achieve high accuracy levels. Naive Bayes classifiers are highly scalable, requiring a number of parameters linear in the number of variables (features/predictors) in a learning problem. Maximum-likelihood training can be done by evaluating a closed-form expression, which takes linear time, rather than by expensive iterative approximation as used for many other types of classifiers.In the statistics literature, naive Bayes models are known under a variety of names, including simple Bayes and independence Bayes. All these names reference the use of Bayes' theorem in the classifier's decision rule, but naive Bayes is not (necessarily) a Bayesian method."
textReview = "I love this product! It's awesome! I would totally kill someone for this product for it to give birth to my offspring. Hail satan and stuff."
textRamblin = "Once upon a time there was a man who did nothing of interest really. He walked around and looked at flowers from time to time. Altough he contributed nothing to society really."
#print(summarize(textBasket, ratio=0.2))
print("\n\n")
print(summarize(textReview, ratio=0.1))
print(summarize(textRamblin, words=20))

#print(summarize(textNB, words=50))